import { Difficulty } from "./difficulty.js";
import { patterns } from "./patterns.js";
import { sites } from "./sites.js";

export function getProblemOfDay() {
  const currentDate = new Date();
  currentDate.toLocaleString("en-US", { timeZone: "Africa/Cairo" });
  return (
    Math.floor(
      (currentDate.getTime() - new Date("2024-04-05T00:00:00").getTime()) /
        (1000 * 3600 * 24)
    ) % problems.length
  );
}

export const problems = [
  {
    title: "Redundant Connection",
    difficulty: null,
    patterns: [patterns.UnionFind],
    url: "https://leetcode.com/problems/redundant-connection/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Jump Game I",
    difficulty: null,
    patterns: [patterns.GreedyTechniques],
    url: "https://leetcode.com/problems/jump-game/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Design HashMap",
    difficulty: null,
    patterns: [patterns.HashMaps],
    url: "https://leetcode.com/problems/design-hashmap/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Snapshot Array",
    difficulty: null,
    patterns: [patterns.CustomDataStructures],
    url: "https://leetcode.com/problems/snapshot-array/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Find the Difference",
    difficulty: null,
    patterns: [patterns.BitwiseManipulation],
    url: "https://leetcode.com/problems/find-the-difference/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Binary Search",
    difficulty: null,
    patterns: [patterns.ModifiedBinarySearch],
    url: "https://leetcode.com/problems/binary-search/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Level Order Traversal of Binary Tree",
    difficulty: null,
    patterns: [patterns.TreeBreadthFirstSearch],
    url: "https://leetcode.com/problems/binary-tree-level-order-traversal/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: patterns.Subsets,
    difficulty: null,
    patterns: [patterns.Subsets],
    url: "https://leetcode.com/problems/subsets/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Maximize Capital",
    difficulty: Difficulty.HARD,
    patterns: [patterns.TwoHeaps],
    url: "https://leetcode.com/problems/ipo/",
    solutions: [
      {
        title: "",
        site: "",
        url: "https://www.youtube.com/watch?v=1IUzNJ6TPEM",
      },
    ],
    companies: [],
    tags: [],
  },
  {
    title: "Basic Calculator",
    difficulty: null,
    patterns: [patterns.Stacks],
    url: "https://leetcode.com/problems/basic-calculator/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Flatten Binary Tree to Linked List",
    difficulty: null,
    patterns: [patterns.TreeDepthFirstSearch],
    url: "https://leetcode.com/problems/flatten-binary-tree-to-linked-list/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "0/1 Knapsack",
    difficulty: null,
    patterns: [patterns.DynamicProgramming],
    url: "https://www.geeksforgeeks.org/0-1-knapsack-problem-dp-10/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Pangram",
    difficulty: Difficulty.EASY,
    patterns: [patterns.Warmup],
    url: "https://leetcode.com/problems/check-if-the-sentence-is-pangram/",
    solutions: [
      {
        title: "",
        site: sites.DesignGurus,
        url: "https://www.designgurus.io/course-play/grokking-the-coding-interview/doc/63d9b9024bb2155485a1a03a",
      },
    ],
    companies: [],
    tags: [],
  },
  {
    title: "Reverse Linked List",
    difficulty: null,
    patterns: [patterns.In_placeReversalOfALinkedList],
    url: "https://leetcode.com/problems/reverse-linked-list/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Set Matrix Zeros",
    difficulty: null,
    patterns: [patterns.Matrices],
    url: "https://leetcode.com/problems/set-matrix-zeroes/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Network Delay Time",
    difficulty: null,
    patterns: [patterns.Graphs],
    url: "https://leetcode.com/problems/network-delay-time/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: patterns.MergeIntervals,
    difficulty: null,
    patterns: [patterns.MergeIntervals],
    url: "https://leetcode.com/problems/merge-intervals/ ",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Missing Number",
    difficulty: null,
    patterns: [patterns.CyclicSort],
    url: "https://leetcode.com/problems/missing-number/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Implement Trie",
    difficulty: null,
    patterns: [patterns.Trie],
    url: "https://leetcode.com/problems/implement-trie-prefix-tree/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Compilation Order",
    difficulty: null,
    patterns: [patterns.TopologicalSort],
    url: "https://www.educative.io/courses/grokking-coding-interview-patterns-java/compilation-order",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Happy Number",
    difficulty: Difficulty.EASY,
    patterns: [patterns.FastAndSlowPointers],
    url: "https://leetcode.com/problems/happy-number/",
    solutions: [
      {
        title: "",
        site: sites.yt,
        url: "https://www.youtube.com/watch?v=ljz85bxOYJ0",
      },
    ],
    companies: [],
    tags: [],
  },
  {
    title: "N-Queens",
    difficulty: null,
    patterns: [patterns.Backtracking],
    url: "https://leetcode.com/problems/n-queens/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Shortest Bridge",
    difficulty: null,
    patterns: [patterns.ChallengeYourself],
    url: "https://leetcode.com/problems/shortest-bridge/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Merge Sorted Array",
    difficulty: null,
    patterns: [patterns.K_wayMerge],
    url: "https://leetcode.com/problems/merge-sorted-array/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Kth Largest Element in a Stream",
    difficulty: null,
    patterns: [patterns.TopKElements],
    url: "https://leetcode.com/problems/kth-largest-element-in-a-stream/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Palindrome Permutation",
    difficulty: null,
    patterns: [patterns.KnowingWhatToTrack],
    url: "https://leetcode.com/problems/palindrome-permutation/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Repeated DNA Sequences",
    difficulty: Difficulty.MEDIUM,
    patterns: [patterns.SlidingWindow],
    url: "https://leetcode.com/problems/repeated-dna-sequences/",
    solutions: [
      {
        title: "",
        site: sites.yt,
        url: "https://www.youtube.com/watch?v=FzTYfsmtOso",
      },
    ],
    companies: [],
    tags: [],
  },
  {
    title: "Valid Palindrome",
    difficulty: Difficulty.EASY,
    patterns: [patterns.TwoPointers],
    url: "https://leetcode.com/problems/valid-palindrome/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Binary Tree Zigzag Level Order Traversal",
    difficulty: null,
    patterns: [patterns.TreeBreadthFirstSearch],
    url: "https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Reorganize String",
    difficulty: null,
    patterns: [patterns.TopKElements],
    url: "https://leetcode.com/problems/reorganize-string/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Complement of Base 10 Number",
    difficulty: null,
    patterns: [patterns.BitwiseManipulation],
    url: "https://leetcode.com/problems/complement-of-base-10-integer/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Linked List Cycle",
    difficulty: null,
    patterns: [patterns.FastAndSlowPointers],
    url: "https://leetcode.com/problems/linked-list-cycle/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Paths in Maze That Lead to Same Room",
    difficulty: null,
    patterns: [patterns.Graphs],
    url: "https://leetcode.com/problems/paths-in-maze-that-lead-to-same-room/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Sum of Three Values | 3Sum Closest",
    difficulty: Difficulty.MEDIUM,
    patterns: [patterns.TwoPointers],
    url: "https://leetcode.com/problems/3sum-closest/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Search in Rotated Sorted Array",
    difficulty: null,
    patterns: [patterns.ModifiedBinarySearch],
    url: "https://leetcode.com/problems/search-in-rotated-sorted-array/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Diameter of Binary Tree",
    difficulty: null,
    patterns: [patterns.TreeDepthFirstSearch],
    url: "https://leetcode.com/problems/diameter-of-binary-tree/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Number of Islands",
    difficulty: null,
    patterns: [patterns.UnionFind],
    url: "https://leetcode.com/problems/number-of-islands/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Find Median from a Data Stream",
    difficulty: null,
    patterns: [patterns.TwoHeaps],
    url: "https://leetcode.com/problems/find-median-from-data-stream/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Permutations",
    difficulty: null,
    patterns: [patterns.Subsets],
    url: "https://leetcode.com/problems/permutations/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Coin Change",
    difficulty: null,
    patterns: [patterns.DynamicProgramming],
    url: "https://leetcode.com/problems/coin-change/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Find Maximum in Sliding Window",
    difficulty: null,
    patterns: [patterns.SlidingWindow],
    url: "https://leetcode.com/problems/sliding-window-maximum/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Insert Interval",
    difficulty: null,
    patterns: [patterns.MergeIntervals],
    url: "https://leetcode.com/problems/insert-interval/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Fraction to Recurring Decimal",
    difficulty: null,
    patterns: [patterns.HashMaps],
    url: "https://leetcode.com/problems/fraction-to-recurring-decimal/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Reverse Nodes in k-Group",
    difficulty: null,
    patterns: [patterns.In_placeReversalOfALinkedList],
    url: "https://leetcode.com/problems/reverse-nodes-in-k-group/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Word Search",
    difficulty: null,
    patterns: [patterns.Backtracking],
    url: "https://leetcode.com/problems/word-search/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Number of Connected Components in an Undirected Graph",
    difficulty: null,
    patterns: [patterns.ChallengeYourself],
    url: "https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Rotate Image",
    difficulty: null,
    patterns: [patterns.Matrices],
    url: "https://leetcode.com/problems/rotate-image/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Valid Anagram",
    difficulty: null,
    patterns: [patterns.KnowingWhatToTrack],
    url: "https://leetcode.com/problems/valid-anagram/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Sqrt",
    difficulty: Difficulty.EASY,
    patterns: [patterns.Warmup],
    url: "https://leetcode.com/problems/sqrtx/description/",
    solutions: [
      {
        title: "",
        site: sites.DesignGurus,
        url: "https://www.designgurus.io/course-play/grokking-the-coding-interview/doc/63d9065f4c5ef6536969a6ab",
      },
    ],
    companies: [],
    tags: [],
  },
  {
    title: "Remove All Adjacent Duplicates In String",
    difficulty: null,
    patterns: [patterns.Stacks],
    url: "https://leetcode.com/problems/remove-all-adjacent-duplicates-in-string/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Time-Based Key-Value Store",
    difficulty: null,
    patterns: [patterns.CustomDataStructures],
    url: "https://leetcode.com/problems/time-based-key-value-store/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "First Missing Positive",
    difficulty: null,
    patterns: [patterns.CyclicSort],
    url: "https://leetcode.com/problems/first-missing-positive/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Search Suggestions System",
    difficulty: null,
    patterns: [patterns.Trie],
    url: "https://leetcode.com/problems/search-suggestions-system/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Kth Smallest Number in M Sorted Lists",
    difficulty: null,
    patterns: [patterns.K_wayMerge],
    url: "https://leetcode.com/problems/kth-smallest-element-in-a-sorted-matrix/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Alien Dictionary",
    difficulty: null,
    patterns: [patterns.TopologicalSort],
    url: "https://leetcode.com/problems/alien-dictionary/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Boats to Save People",
    difficulty: null,
    patterns: [patterns.GreedyTechniques],
    url: "https://leetcode.com/problems/boats-to-save-people/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Interval List Intersections",
    difficulty: null,
    patterns: [patterns.MergeIntervals],
    url: "https://leetcode.com/problems/interval-list-intersections/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Implement LRU Cache",
    difficulty: null,
    patterns: [patterns.CustomDataStructures],
    url: "https://leetcode.com/problems/lru-cache/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Minimum Window Subsequence",
    difficulty: null,
    patterns: [patterns.SlidingWindow],
    url: "https://leetcode.com/problems/minimum-window-substring/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Minimum Remove to Make Valid Parentheses",
    difficulty: null,
    patterns: [patterns.Stacks],
    url: "https://leetcode.com/problems/minimum-remove-to-make-valid-parentheses/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "First Bad Version",
    difficulty: null,
    patterns: [patterns.ModifiedBinarySearch],
    url: "https://leetcode.com/problems/first-bad-version/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "House Robber III",
    difficulty: null,
    patterns: [patterns.Backtracking],
    url: "https://leetcode.com/problems/house-robber-iii/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "K Closest Points to Origin",
    difficulty: null,
    patterns: [patterns.TopKElements],
    url: "https://leetcode.com/problems/k-closest-points-to-origin/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Most Stones Removed with Same Row or Column",
    difficulty: null,
    patterns: [patterns.UnionFind],
    url: "https://leetcode.com/problems/most-stones-removed-with-same-row-or-column",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Flipping an Image",
    difficulty: null,
    patterns: [patterns.BitwiseManipulation],
    url: "https://leetcode.com/problems/flipping-an-image/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Find the Corrupt Pair",
    difficulty: null,
    patterns: [patterns.CyclicSort],
    url: "https://leetcode.com/problems/set-mismatch/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Middle of the Linked List",
    difficulty: null,
    patterns: [patterns.FastAndSlowPointers],
    url: "https://leetcode.com/problems/middle-of-the-linked-list/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Design Tic-Tac-Toe",
    difficulty: null,
    patterns: [patterns.KnowingWhatToTrack],
    url: "https://leetcode.com/problems/design-tic-tac-toe/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Letter Combinations of a Phone Number",
    difficulty: null,
    patterns: [patterns.Subsets],
    url: "https://leetcode.com/problems/letter-combinations-of-a-phone-number/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "N-th Tribonacci Number",
    difficulty: null,
    patterns: [patterns.DynamicProgramming],
    url: "https://leetcode.com/problems/n-th-tribonacci-number/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Reverse Linked List II",
    difficulty: null,
    patterns: [patterns.In_placeReversalOfALinkedList],
    url: "https://leetcode.com/problems/reverse-linked-list-ii/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Find K Pairs with Smallest Sums",
    difficulty: null,
    patterns: [patterns.K_wayMerge],
    url: "https://leetcode.com/problems/find-k-pairs-with-smallest-sums/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Remove nth Node from End of List",
    difficulty: Difficulty.MEDIUM,
    patterns: [patterns.TwoPointers],
    url: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Gas Stations",
    difficulty: Difficulty.MEDIUM,
    patterns: [patterns.GreedyTechniques],
    url: "https://leetcode.com/problems/gas-station/",
    solutions: [
      {
        title: "",
        site: sites.yt,
        url: "https://www.youtube.com/watch?v=lJwbPZGo05A",
      },
    ],
    companies: [],
    tags: [],
  },
  {
    title: "Reverse Vowels",
    difficulty: Difficulty.EASY,
    patterns: [patterns.Warmup],
    url: "https://leetcode.com/problems/reverse-vowels-of-a-string/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Serialize and Deserialize Binary Tree",
    difficulty: null,
    patterns: [patterns.TreeDepthFirstSearch],
    url: "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Sliding Window Median",
    difficulty: null,
    patterns: [patterns.TwoHeaps],
    url: "https://leetcode.com/problems/sliding-window-median/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Spiral Matrix",
    difficulty: null,
    patterns: [patterns.Matrices],
    url: "https://leetcode.com/problems/spiral-matrix/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Replace Words",
    difficulty: null,
    patterns: [patterns.Trie],
    url: "https://leetcode.com/problems/replace-words/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Logger Rate Limiter",
    difficulty: null,
    patterns: [patterns.HashMaps],
    url: "https://leetcode.com/problems/logger-rate-limiter/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Clone Graph",
    difficulty: null,
    patterns: [patterns.Graphs],
    url: "https://leetcode.com/problems/clone-graph",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Verifying an Alien Dictionary",
    difficulty: null,
    patterns: [patterns.TopologicalSort],
    url: "https://leetcode.com/problems/verifying-an-alien-dictionary/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Populating Next Right Pointers in Each Node",
    difficulty: null,
    patterns: [patterns.TreeBreadthFirstSearch],
    url: "https://leetcode.com/problems/populating-next-right-pointers-in-each-node/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Pacific Atlantic Water Flow",
    difficulty: null,
    patterns: [patterns.ChallengeYourself],
    url: "https://leetcode.com/problems/pacific-atlantic-water-flow/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Partition Equal Subset Sum",
    difficulty: null,
    patterns: [patterns.DynamicProgramming],
    url: "https://leetcode.com/problems/partition-equal-subset-sum/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Restore IP Addresses",
    difficulty: null,
    patterns: [patterns.Backtracking],
    url: "https://leetcode.com/problems/restore-ip-addresses/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Design Add and Search Words Data Structure",
    difficulty: null,
    patterns: [patterns.Trie],
    url: "https://leetcode.com/problems/design-add-and-search-words-data-structure/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Kth Smallest Element in a Sorted Matrix",
    difficulty: null,
    patterns: [patterns.K_wayMerge],
    url: "https://leetcode.com/problems/kth-smallest-element-in-a-sorted-matrix/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Sort Colors",
    difficulty: null,
    patterns: [patterns.TwoPointers],
    url: "https://leetcode.com/problems/sort-colors/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Single Number",
    difficulty: null,
    patterns: [patterns.BitwiseManipulation],
    url: "https://leetcode.com/problems/single-number/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Longest Consecutive Sequence",
    difficulty: null,
    patterns: [patterns.UnionFind],
    url: "https://leetcode.com/problems/longest-consecutive-sequence",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Where Will the Ball Fall",
    difficulty: null,
    patterns: [patterns.Matrices],
    url: "https://leetcode.com/problems/where-will-the-ball-fall/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Insert Delete GetRandom O(1",
    difficulty: null,
    patterns: [patterns.CustomDataStructures],
    url: "https://leetcode.com/problems/insert-delete-getrandom-o1/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Employee Free Time",
    difficulty: null,
    patterns: [patterns.MergeIntervals],
    url: "https://leetcode.com/problems/employee-free-time/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Two City Scheduling",
    difficulty: null,
    patterns: [patterns.GreedyTechniques],
    url: "https://leetcode.com/problems/two-city-scheduling/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Next Greater Element",
    difficulty: null,
    patterns: [patterns.HashMaps],
    url: "https://leetcode.com/problems/next-greater-element-i/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Circular Array Loop",
    difficulty: null,
    patterns: [patterns.FastAndSlowPointers],
    url: "https://leetcode.com/problems/circular-array-loop/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Course Schedule",
    difficulty: null,
    patterns: [patterns.TopologicalSort],
    url: "https://leetcode.com/problems/course-schedule/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Random Pick with Weight",
    difficulty: null,
    patterns: [patterns.ModifiedBinarySearch],
    url: "https://leetcode.com/problems/random-pick-with-weight/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Vertical Order Traversal of a Binary Tree",
    difficulty: null,
    patterns: [patterns.TreeBreadthFirstSearch],
    url: "https://leetcode.com/problems/vertical-order-traversal-of-a-binary-tree/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Find the First K Missing Positive Numbers",
    difficulty: null,
    patterns: [patterns.CyclicSort],
    url: "https://leetcode.com/problems/kth-missing-positive-number/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Schedule Tasks on Minimum Machines",
    difficulty: null,
    patterns: [patterns.TwoHeaps],
    url: "https://leetcode.com/problems/task-scheduler/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Group Anagrams",
    difficulty: null,
    patterns: [patterns.KnowingWhatToTrack],
    url: "https://leetcode.com/problems/group-anagrams/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Longest Repeating Character Replacement",
    difficulty: null,
    patterns: [patterns.SlidingWindow],
    url: "https://leetcode.com/problems/longest-repeating-character-replacement/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Top K Frequent Elements",
    difficulty: null,
    patterns: [patterns.TopKElements],
    url: "https://leetcode.com/problems/top-k-frequent-elements/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Flatten Nested List Iterator",
    difficulty: null,
    patterns: [patterns.Stacks],
    url: "https://leetcode.com/problems/flatten-nested-list-iterator/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Contains Duplicate",
    difficulty: Difficulty.EASY,
    patterns: [patterns.ChallengeYourself],
    url: "https://leetcode.com/problems/contains-duplicate/",
    solutions: [
      {
        title: "",
        site: sites.DesignGurus,
        url: "https://www.designgurus.io/course-play/grokking-the-coding-interview/doc/63d906094c5ef6536969a376",
      },
    ],
    companies: [],
    tags: [],
  },
  {
    title: "Shortest Word Distance",
    difficulty: Difficulty.EASY,
    patterns: [patterns.Warmup],
    url: "https://leetcode.ca/all/243.html",
    solutions: [
      {
        title: "",
        site: "",
        url: "https://aaronice.gitbook.io/lintcode/hash-table/shortest-word-distance",
      },
    ],
    companies: [],
    tags: [],
  },
  {
    title: "Graph Valid Tree",
    difficulty: null,
    patterns: [patterns.Graphs],
    url: "https://leetcode.com/problems/graph-valid-tree/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Invert Binary Tree",
    difficulty: null,
    patterns: [patterns.TreeDepthFirstSearch],
    url: "https://leetcode.com/problems/invert-binary-tree/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Generate Parentheses",
    difficulty: null,
    patterns: [patterns.Subsets],
    url: "https://leetcode.com/problems/generate-parentheses/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Reorder List",
    difficulty: Difficulty.MEDIUM,
    patterns: [patterns.In_placeReversalOfALinkedList],
    url: "https://leetcode.com/problems/reorder-list/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Exclusive Execution Time of Functions",
    difficulty: null,
    patterns: [patterns.Stacks],
    url: "https://leetcode.com/problems/exclusive-time-of-functions/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Longest Substring without Repeating Characters",
    difficulty: null,
    patterns: [patterns.SlidingWindow],
    url: "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Jump Game II",
    difficulty: null,
    patterns: [patterns.GreedyTechniques],
    url: "https://leetcode.com/problems/jump-game-ii/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Merge K Sorted Lists",
    difficulty: null,
    patterns: [patterns.K_wayMerge],
    url: "https://leetcode.com/problems/merge-k-sorted-lists/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Word Search II",
    difficulty: null,
    patterns: [patterns.Trie],
    url: "https://leetcode.com/problems/word-search-ii/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Maximum Subarray",
    difficulty: null,
    patterns: [patterns.ChallengeYourself],
    url: "https://leetcode.com/problems/maximum-subarray/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Course Schedule II",
    difficulty: null,
    patterns: [patterns.TopologicalSort],
    url: "https://leetcode.com/problems/course-schedule-ii/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Bus Routes",
    difficulty: null,
    patterns: [patterns.Graphs],
    url: "https://leetcode.com/problems/bus-routes/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Two Single Numbers",
    difficulty: null,
    patterns: [patterns.BitwiseManipulation],
    url: "https://leetcode.com/problems/single-number-iii/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Symmetric Tree",
    difficulty: null,
    patterns: [patterns.TreeBreadthFirstSearch],
    url: "https://leetcode.com/problems/symmetric-tree",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Number of Good Pairs",
    difficulty: Difficulty.EASY,
    patterns: [patterns.Warmup],
    url: "https://leetcode.com/problems/number-of-good-pairs/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Palindrome Linked List",
    difficulty: null,
    patterns: [patterns.FastAndSlowPointers],
    url: "https://leetcode.com/problems/palindrome-linked-list/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Task Scheduler",
    difficulty: null,
    patterns: [patterns.MergeIntervals],
    url: "https://leetcode.com/problems/task-scheduler/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Kth Largest Element in an Array",
    difficulty: null,
    patterns: [patterns.TopKElements],
    url: "https://leetcode.com/problems/kth-largest-element-in-an-array/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Last Day Where You Can Still Cross",
    difficulty: null,
    patterns: [patterns.UnionFind],
    url: "https://leetcode.com/problems/last-day-where-you-can-still-cross/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Swapping Nodes in a Linked List",
    difficulty: null,
    patterns: [patterns.In_placeReversalOfALinkedList],
    url: "https://leetcode.com/problems/swapping-nodes-in-a-linked-list/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Find K-Sum Subsets",
    difficulty: null,
    patterns: [patterns.Subsets],
    url: "https://leetcode.com/problems/subarray-sum-equals-k/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Find K Closest Elements",
    difficulty: null,
    patterns: [patterns.ModifiedBinarySearch],
    url: "https://leetcode.com/problems/find-k-closest-elements/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Sudoku Solver",
    difficulty: null,
    patterns: [patterns.Backtracking],
    url: "https://leetcode.com/problems/sudoku-solver/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Counting Bits",
    difficulty: null,
    patterns: [patterns.DynamicProgramming],
    url: "https://leetcode.com/problems/counting-bits/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Convert Sorted Array to Binary Search Tree",
    difficulty: null,
    patterns: [patterns.TreeDepthFirstSearch],
    url: "https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Min Stack",
    difficulty: null,
    patterns: [patterns.CustomDataStructures],
    url: "https://leetcode.com/problems/min-stack/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Valid Palindrome II",
    difficulty: null,
    patterns: [patterns.TwoPointers],
    url: "https://leetcode.com/problems/valid-palindrome-ii/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Isomorphic Strings",
    difficulty: null,
    patterns: [patterns.HashMaps],
    url: "https://leetcode.com/problems/isomorphic-strings/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Maximum Frequency Stack",
    difficulty: null,
    patterns: [patterns.KnowingWhatToTrack],
    url: "https://leetcode.com/problems/maximum-frequency-stack/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Lexicographical Numbers",
    difficulty: null,
    patterns: [patterns.Trie],
    url: "https://leetcode.com/problems/lexicographical-numbers/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Reverse Words in a String",
    difficulty: null,
    patterns: [patterns.TwoPointers],
    url: "https://leetcode.com/problems/reverse-words-in-a-string/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Regions Cut by Slashes",
    difficulty: null,
    patterns: [patterns.UnionFind],
    url: "https://leetcode.com/problems/regions-cut-by-slashes/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "LFU Cache",
    difficulty: null,
    patterns: [patterns.CustomDataStructures],
    url: "https://leetcode.com/problems/lfu-cache/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Top K Frequent Words",
    difficulty: null,
    patterns: [patterns.TopKElements],
    url: "https://leetcode.com/problems/top-k-frequent-words/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Find All Possible Recipes from Given Supplies",
    difficulty: null,
    patterns: [patterns.TopologicalSort],
    url: "https://leetcode.com/problems/find-all-possible-recipes-from-given-supplies/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Valid Parentheses",
    difficulty: null,
    patterns: [patterns.Stacks],
    url: "https://leetcode.com/problems/valid-parentheses/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Meeting Rooms II",
    difficulty: null,
    patterns: [patterns.MergeIntervals],
    url: "https://leetcode.com/problems/meeting-rooms-ii/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Reverse Bits",
    difficulty: null,
    patterns: [patterns.BitwiseManipulation],
    url: "https://leetcode.com/problems/reverse-bits/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Search in Rotated Sorted Array II",
    difficulty: null,
    patterns: [patterns.ModifiedBinarySearch],
    url: "https://leetcode.com/problems/search-in-rotated-sorted-array-ii/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "First Unique Character in a String",
    difficulty: null,
    patterns: [patterns.KnowingWhatToTrack],
    url: "https://leetcode.com/problems/first-unique-character-in-a-string/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Swap Nodes in Pairs",
    difficulty: Difficulty.MEDIUM,
    patterns: [patterns.In_placeReversalOfALinkedList],
    url: "https://leetcode.com/problems/swap-nodes-in-pairs/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Flood Fill",
    difficulty: null,
    patterns: [patterns.Backtracking],
    url: "https://leetcode.com/problems/flood-fill/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Minimum Window Substring",
    difficulty: null,
    patterns: [patterns.SlidingWindow],
    url: "https://leetcode.com/problems/minimum-window-substring/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Build Binary Tree from Preorder and Inorder Traversal",
    difficulty: null,
    patterns: [patterns.TreeDepthFirstSearch],
    url: "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Find Minimum in Rotated Sorted Array",
    difficulty: null,
    patterns: [patterns.ChallengeYourself],
    url: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Word Ladder",
    difficulty: null,
    patterns: [patterns.TreeBreadthFirstSearch],
    url: "https://leetcode.com/problems/word-ladder",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "01 Matrix",
    difficulty: null,
    patterns: [patterns.DynamicProgramming],
    url: "https://leetcode.com/problems/01-matrix/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Encode and Decode Strings",
    difficulty: null,
    patterns: [patterns.BitwiseManipulation],
    url: "https://leetcode.ca/2016-08-27-271-Encode-and-Decode-Strings/",
    solutions: [
      {
        title: "",
        site: "",
        url: "https://algo.monster/liteproblems/271",
      },
    ],
    companies: [],
    tags: [],
  },
  {
    title: "Find The Duplicate Number",
    difficulty: null,
    patterns: [patterns.FastAndSlowPointers],
    url: "https://leetcode.com/problems/find-the-duplicate-number/",
    solutions: [
      {
        title: "",
        site: sites.yt,
        url: "https://www.youtube.com/watch?v=pKO9UjSeLew",
      },
      {
        title: "",
        site: sites.yt,
        url: "https://www.youtube.com/watch?v=9YTjXqqJEFE",
      },
    ],
    companies: [],
    tags: [],
  },
  {
    title: "Find All Anagrams in a String",
    difficulty: null,
    patterns: [patterns.KnowingWhatToTrack],
    url: "https://leetcode.com/problems/find-all-anagrams-in-a-string/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Connect All Siblings of a Binary Tree",
    difficulty: null,
    patterns: [patterns.TreeBreadthFirstSearch],
    url: "https://leetcode.com/problems/populating-next-right-pointers-in-each-node/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Implement Queue Using Stacks",
    difficulty: null,
    patterns: [patterns.Stacks],
    url: "https://leetcode.com/problems/implement-queue-using-stacks/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Minimum Number of Refueling Stops",
    difficulty: null,
    patterns: [patterns.GreedyTechniques],
    url: "https://leetcode.com/problems/minimum-number-of-refueling-stops/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Non-overlapping Intervals",
    difficulty: null,
    patterns: [patterns.ChallengeYourself],
    url: "https://leetcode.com/problems/non-overlapping-intervals/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "House Robber II",
    difficulty: null,
    patterns: [patterns.DynamicProgramming],
    url: "https://leetcode.com/problems/house-robber-ii/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Best Time to Buy and Sell Stock",
    difficulty: null,
    patterns: [patterns.SlidingWindow],
    url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Median of Two Sorted Arrays",
    difficulty: null,
    patterns: [patterns.K_wayMerge],
    url: "https://leetcode.com/problems/median-of-two-sorted-arrays/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Accounts Merge",
    difficulty: null,
    patterns: [patterns.UnionFind],
    url: "https://leetcode.com/problems/accounts-merge",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Binary Tree Right Side View",
    difficulty: null,
    patterns: [patterns.TreeDepthFirstSearch],
    url: "https://leetcode.com/problems/binary-tree-right-side-view/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Binary Tree Maximum Path Sum",
    difficulty: null,
    patterns: [patterns.TreeDepthFirstSearch],
    url: "https://leetcode.com/problems/binary-tree-maximum-path-sum/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Ransom Note",
    difficulty: null,
    patterns: [patterns.KnowingWhatToTrack],
    url: "https://leetcode.com/problems/ransom-note/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Meeting Rooms",
    difficulty: null,
    patterns: [patterns.ChallengeYourself],
    url: "https://leetcode.com/problems/meeting-rooms/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Evaluate Division",
    difficulty: null,
    patterns: [patterns.UnionFind],
    url: "https://leetcode.com/problems/evaluate-division/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Minimum Size Subarray Sum",
    difficulty: Difficulty.MEDIUM,
    patterns: [patterns.SlidingWindow],
    url: "https://leetcode.com/problems/minimum-size-subarray-sum/",
    solutions: [
      {
        title: "",
        site: sites.yt,
        url: "https://www.youtube.com/watch?v=aYqYMIqZx5s",
      },
    ],
    companies: [],
    tags: [],
  },
  {
    title: "Maximum Product Subarray",
    difficulty: null,
    patterns: [patterns.DynamicProgramming],
    url: "https://leetcode.com/problems/maximum-product-subarray/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Longest Palindrome",
    difficulty: null,
    patterns: [patterns.HashMaps],
    url: "https://leetcode.com/problems/longest-palindrome/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Single Element in a Sorted Array",
    difficulty: null,
    patterns: [patterns.ModifiedBinarySearch],
    url: "https://leetcode.com/problems/single-element-in-a-sorted-array/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Lowest Common Ancestor in a Binary Tree",
    difficulty: null,
    patterns: [patterns.TreeDepthFirstSearch],
    url: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Combination Sum",
    difficulty: null,
    patterns: [patterns.DynamicProgramming],
    url: "https://leetcode.com/problems/combination-sum/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Two Sum",
    difficulty: null,
    patterns: [patterns.ChallengeYourself],
    url: "https://leetcode.com/problems/two-sum/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Longest Palindrome by Concatenating Two-Letter Words",
    difficulty: Difficulty.MEDIUM,
    patterns: [patterns.KnowingWhatToTrack],
    url: "https://leetcode.com/problems/longest-palindrome-by-concatenating-two-letter-words/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Reverse Nodes In Even Length Groups",
    difficulty: null,
    patterns: [patterns.In_placeReversalOfALinkedList],
    url: "https://leetcode.com/problems/reverse-nodes-in-even-length-groups/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Palindromic Substrings",
    difficulty: null,
    patterns: [patterns.DynamicProgramming],
    url: "https://leetcode.com/problems/palindromic-substrings/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Matchsticks to Square",
    difficulty: null,
    patterns: [patterns.Backtracking],
    url: "https://leetcode.com/problems/matchsticks-to-square/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Minimize Malware Spread",
    difficulty: null,
    patterns: [patterns.UnionFind],
    url: "https://leetcode.com/problems/minimize-malware-spread/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Validate Binary Search Tree",
    difficulty: null,
    patterns: [patterns.TreeDepthFirstSearch],
    url: "https://leetcode.com/problems/validate-binary-search-tree/description/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Subtree of Another Tree",
    difficulty: null,
    patterns: [patterns.ChallengeYourself],
    url: "https://leetcode.com/problems/subtree-of-another-tree/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Word Break",
    difficulty: null,
    patterns: [patterns.DynamicProgramming],
    url: "https://leetcode.com/problems/word-break/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Largest Rectangle in Histogram",
    difficulty: null,
    patterns: [patterns.ChallengeYourself],
    url: "https://leetcode.com/problems/largest-rectangle-in-histogram/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Maximum Depth of Binary Tree",
    difficulty: null,
    patterns: [patterns.TreeDepthFirstSearch],
    url: "https://leetcode.com/problems/maximum-depth-of-binary-tree/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Longest Common Subsequence",
    difficulty: null,
    patterns: [patterns.DynamicProgramming],
    url: "https://leetcode.com/problems/longest-common-subsequence/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Kth Smallest Element in a BST",
    difficulty: null,
    patterns: [patterns.TreeDepthFirstSearch],
    url: "https://leetcode.com/problems/kth-smallest-element-in-a-bst",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Number of 1 Bits",
    difficulty: null,
    patterns: [patterns.ChallengeYourself],
    url: "https://leetcode.com/problems/number-of-1-bits/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Sort List",
    difficulty: null,
    patterns: [patterns.ChallengeYourself],
    url: "https://leetcode.com/problems/sort-list/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Word Break II",
    difficulty: null,
    patterns: [patterns.DynamicProgramming],
    url: "https://leetcode.com/problems/word-break-ii/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Container With the Most Water",
    difficulty: null,
    patterns: [patterns.ChallengeYourself],
    url: "https://leetcode.com/problems/container-with-most-water/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Decode Ways",
    difficulty: null,
    patterns: [patterns.DynamicProgramming],
    url: "https://leetcode.com/problems/decode-ways/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Climbing Stairs",
    difficulty: null,
    patterns: [patterns.DynamicProgramming],
    url: "https://leetcode.com/problems/climbing-stairs/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "4Sum",
    difficulty: null,
    patterns: [patterns.ChallengeYourself],
    url: "https://leetcode.com/problems/4sum/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Evaluate Reverse Polish Notation",
    difficulty: null,
    patterns: [patterns.ChallengeYourself],
    url: "https://leetcode.com/problems/evaluate-reverse-polish-notation/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Loud and Rich",
    difficulty: null,
    patterns: [patterns.ChallengeYourself],
    url: "https://leetcode.com/problems/loud-and-rich/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Product of Array Except Self",
    difficulty: null,
    patterns: [patterns.ChallengeYourself],
    url: "https://leetcode.com/problems/product-of-array-except-self/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Longest Increasing Subsequence",
    difficulty: null,
    patterns: [patterns.ChallengeYourself],
    url: "https://leetcode.com/problems/longest-increasing-subsequence/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Sum of Two Integers",
    difficulty: null,
    patterns: [patterns.ChallengeYourself],
    url: "https://leetcode.com/problems/sum-of-two-integers/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Majority Element",
    difficulty: null,
    patterns: [patterns.ChallengeYourself],
    url: "https://leetcode.com/problems/majority-element/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Unique Paths",
    difficulty: null,
    patterns: [patterns.ChallengeYourself],
    url: "https://leetcode.com/problems/unique-paths/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Longest Palindromic Substring",
    difficulty: null,
    patterns: [patterns.ChallengeYourself],
    url: "https://leetcode.com/problems/longest-palindromic-substring/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Permutations II",
    difficulty: null,
    patterns: [patterns.ChallengeYourself],
    url: "https://leetcode.com/problems/permutations-ii/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Number of Provinces",
    difficulty: null,
    patterns: [patterns.ChallengeYourself],
    url: "https://leetcode.com/problems/number-of-provinces/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Linked List Cycle II",
    difficulty: null,
    patterns: [patterns.ChallengeYourself],
    url: "https://leetcode.com/problems/linked-list-cycle-ii/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Minimum Flips to Make the Binary String Alternate",
    difficulty: null,
    patterns: [patterns.ChallengeYourself],
    url: "https://leetcode.com/problems/minimum-number-of-flips-to-make-the-binary-string-alternating/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Lemonade Change",
    difficulty: null,
    patterns: [patterns.ChallengeYourself],
    url: "https://leetcode.com/problems/lemonade-change/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "House Robber",
    difficulty: null,
    patterns: [patterns.ChallengeYourself],
    url: "https://leetcode.com/problems/house-robber/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Find All Numbers Disappeared in an Array",
    difficulty: null,
    patterns: [patterns.ChallengeYourself],
    url: "https://leetcode.com/problems/find-all-numbers-disappeared-in-an-array/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Find All Duplicates in an Array",
    difficulty: null,
    patterns: [patterns.ChallengeYourself],
    url: "https://leetcode.com/problems/find-all-duplicates-in-an-array/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Same Tree",
    difficulty: null,
    patterns: [patterns.ChallengeYourself],
    url: "https://leetcode.com/problems/same-tree/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Design In-Memory File System",
    difficulty: null,
    patterns: [patterns.ChallengeYourself],
    url: "https://leetcode.com/problems/design-in-memory-file-system/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Design File System",
    difficulty: null,
    patterns: [patterns.ChallengeYourself],
    url: "https://leetcode.com/problems/design-file-system/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Asteroid Collision",
    difficulty: null,
    patterns: [patterns.ChallengeYourself],
    url: "https://leetcode.com/problems/asteroid-collision/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Rotting Oranges",
    difficulty: null,
    patterns: [patterns.ChallengeYourself],
    url: "https://leetcode.com/problems/rotting-oranges/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Add Binary",
    difficulty: null,
    patterns: [patterns.ChallengeYourself],
    url: "https://leetcode.com/problems/add-binary/",
    solutions: [],
    companies: [],
    tags: [],
  },
  {
    title: "Multiply Strings",
    difficulty: null,
    patterns: [patterns.ChallengeYourself],
    url: "https://leetcode.com/problems/multiply-strings",
    solutions: [],
    companies: [],
    tags: [],
  },
];
